electro-smith/DaisySP

.gitattributes

I've noticed a lot of line-ending issues reviewing diffs and working in the repo. Here's a proposal that keeps the forces the windows EOL on VisualStudio files and opts for automatic line endings on everything else. If there is a specific reason the line endings handling was not the default lmk.
Here's a helpful link I found, it also covers how to clean up your line endings automatically in your repo:
https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

Updating line-ending settings to play nicer across platforms

---

.travis.yml

This helps developers to use Travis CI when working on their forks. Without this, builds will fail on forks because deployment of the docs is not possible.
For  `electro-smith/DaisySP` enable deployment by setting up `DEPLOY_DOCS=1` in Travis CI.

Made docs deployment conditional

---

modules/adenv.cpp

explicitly sets output to 0.0 when idling to avoid non-silent low amplitude output during idle

Adenv Silence fix

---

modules/adenv.cpp

Calculates end of cycle based on output value rather than calculated segment time. Also allows for segments to be updated while they are playing, rather than between segments.

AdEnv bugfix

---

modules/compressor.cpp
modules/compressor.h
modules/dsp.h

Improved the compressor a lot, as this was one of the modules I currently use most. Would appreciate any feedback 👍 
Some changes I made:
- pulled gain calculation and reduction apart for monitoring and multichannel support (now has an Apply() function to apply gain reduction to a signal without calculating the reduction, and GetGain() to get the gain reduction in dB)
- improved readability by moving away from the faust internal names
- improved makeup-gain calculations (I _think_ this is correct, at least it sounds like that and this is based on another faust implementation, but I'm not _completely_ sure)
- changing parameters now costs a lot less (only calculating the affected internals on parameter changes)
- a lot less expensive, eliminating useless variables, more inlining and using …

Compressor improvement

---

Makefile

added language standards to Makefile instead of relying on compiler defaults.
Currently set to:
gnu11 for C
gnu++14 for C++
This resolves #32

Language Standards in Makefile

---

modules/atone.cpp
modules/balance.cpp
modules/biquad.cpp
modules/crossfade.cpp
modules/decimator.h
modules/metro.cpp
modules/phasor.cpp
modules/pitchshifter.h
modules/svf.cpp
modules/tone.cpp

Cosmetic consistency update.
All modules are updated to use math constants from dsp.h, such as 
PI_F, TWOPI_F, HALFPI_F, etc.
Also in several places implicit type casts were replaced by explicit ones to get rid of warnings.

use constants from dsp.h throughout the modules

---

CMakeLists.txt

So there's been a draft for the computer build (#5) for a really long time. The few times I've messed around I have been able  to get it to build (or just grabbed the files to include in whatever I was working on).
It may be a better idea to leave the `Makefile` in place as a standalone build for ARM, and have CMake be the primary build system generator for all other platforms. (Eventually we could have the cmake file generate the ARM build as well). But this seems like a good compromise, and it only requires adding one file.
I'm working on a few example programs for PCs that use DaisySP (primarily a JUCE plugin, and a VCV Rack plugin) that will need to be able to build the library.
I've already tested creating a project with JUCE and DaisySP using cmake that was able to be up and running …

Added CMakeLists file for building on PC

---

modules/nlfilt.cpp
modules/reverbsc.cpp

replaced memset with a loop to quell vs studio build error.
This actually seems like a bigger issue introduced when one of the recent modules was added. Since VS claims it can't find these, even when directly including `"string.h"` or `<cstring>` in the cpp file.
Could be another header guard duplicate as that did cause an issue before, but all of the examples are still building correctly so I find that unlikely.  Apparently this also popped up in #127 .
This at least temporarily resolves the build error.

VS build issue related to memset

---

modules/oscillator.h

A small fixup in the `Oscillator::IsEOC` documentation

[Doc] Fix IsEOC description

---

CMakeLists.txt

Hello, DaisySP team.
When I was developing my application, I found a problem that could not resolve a reference of `daisysp::Phaser` functions.
The reason for this is that adding the Phaser source code in CMake is forgotten.
Please check it.

[CMake] Added missing files of phaser effect.

---

Source/Utility/dsp.h

I was having some issues compiling DaisySP on Windows 10 with MSVC to use in conjunction with JUCE, and found that an ARM-specific opcode was being inserted into the dsp.h header file regardless of the platform. Simply checking if the \_\_arm\_\_ define is set fixes the issue.

Fixed missing __arm__ check before ARM assembly opcode

---

Source/Utility/dsp.h

fixes #156 - added guard around constexpr to prevent issues with c++11 compatibility.

Adds guard around constexpr function to allow C++11 compatibility

---

Source/Control/adsr.cpp
Source/Control/adsr.h

That's a much leaner version of the envelope based on a first order SVF.
Improvements:
- exact attack time
- exact decay time for 1/e target value @ sustain = 0.f;
- no residual output
- added Retrigger
- no time constant calculation on every process call
- Init() takes a block size argument, which us useful for processing control elements only once per audio call back.

Adsr remake

---

Source/Utility/looper.h

fixes #169 - change constant value for frip decay from std::sin to fixed value.

Looper - Updated Frip Decay value to use explicit value instead of sin constexpr

---

Source/Synthesis/oscillator.cpp
Source/Synthesis/oscillator.h

This change implements a configurable pulse width for the `Oscillator` class's square and polyBLEP square waveforms.
Motivation is to add a simple pulse width setting to the standard `Oscillator` class for utility as an audio waveform as well as modulation. The setting applies to both the non-bandlimited and bandlimited square waves. This ended up being rather simple.
_Dropbox links to wav files. All examples start at A=110Hz and go up 4 octaves from there._
* [Slow Sine Sweep of PW - Standard Square Wave (non-bandlimited)](https://www.dropbox.com/s/tnjsqgd0oe0gj7b/PW%20Sweep%20-%205s%20-%20Non%20Bandimited.wav?dl=0)
* [Slow Sine Sweep of PW - polyBLEP Square Wave (bandlimited)](https://www.dropbox.com/s/vhj5e2k12j9cui7/PW%20Sweep%20-%205s%20-%20Bandimited.wav?dl=0)
* [2.5hz Sine PWM - …

Add pulse width setting to Oscillator class for square waveforms

---

Source/Filters/tone.cpp
Source/Filters/tone.h

Very small change to the interface of `Tone` to accept a `float` param for the `SetCutoff` and `Process` methods by value instead of by reference.
The reason for the change is twofold:
1. Passing a cutoff freq by reference prevents usage of rvalues including constant literals, so e.g. `tone.SetFreq(5000.0f)` will not compile.
2. Passing a non-const reference would allow the reference to be modified by the method, which is obviously not the intention of the interface here.

Don't pass Tone float params by reference

---

Source/Effects/decimator.cpp
Source/Effects/decimator.h

Added boolean option SetSmoothCrushing() to Decimator effect.
When it is enabled and bitcrushing amount is set with SetBitcrushFactor(), the bitcrushing effect doesn't jump discretely between bits, but is smoother, or has "fractional bits". When exact number of bits to crush is set with SetBitsToCrush(), smooth crushing is disabled automatically.

Added option for smoother bitcrushing in Decimator

---

Source/Control/adenv.cpp

Fix for an issue where if an envelope was re-triggered when it was at the very end of the attack stage it could get locked and never complete. This was because c_inc_ could become so small (due to the delta between the current value and the target value being very small, and then divided by the sample rate) that when added to val the value of val does not change (due to floating point inaccuracies). Ensure c_inc_ is at least as big as std epsilon, so that it will always cause val to change.
[This is my first ever pull request, so apologies if this is not the correct way to contribute to DaisySP]

Fix for numerical error

---

Source/Control/adenv.cpp

Without this include my build would fail with:
```
Ricardo@XXX MINGW64 ~/code/audio/DaisyExamples/DaisySP ((ed11433...))
$ make clean; make
rm -fR build
mkdir build        
arm-none-eabi-g++ -c -mcpu=cortex-m7 -mthumb -mfpu=fpv5-d16 -mfloat-abi=hard -DSTM32H750xx  -ISource -ISource/Control -ISource/Drums -ISource/Dynamics -ISource/Effects -ISource/Filters -ISource/Noise -ISource/PhysicalModeling -ISource/Synthesis -ISource/Utility  -O3 -Wall -Werror -fdata-sections -ffunction-sections -MMD -MP -MF"build/adenv.d" -MT"build/adenv.d" -fno-exceptions -finline-functions  -std=c++14 -static -Wa,-a,-ad,-alms=build/adenv.lst Source/Control/adenv.cpp -o build/adenv.o
Source/Control/adenv.cpp: In member function 'float daisysp::AdEnv::Process()':
Source/Control/adenv.cpp:119:40: error: …
```

Fix missing <limits> include

---

Source/Synthesis/oscillator.cpp
Source/Synthesis/oscillator.h

Fixes bug in leaky integration in `Oscillator` polyblep triangle implementation and changes `Oscillator` to use normalized phase to save a handful of multiplications in all but one case (sine).
Firstly, this changes the range of the `phase_` and `phase_inc_` variables in `Oscillator` from the previous range of 0 - 2pi to a normalized unit range of 0 - 1. The rationale for this is that the only oscillator waveform case that actually needs the 2pi radian scaled range is the sine wave - all the rest of the waveforms don't require radian units at all, and in fact have to use extra multiplications (sometimes multiple times) to normalize back to unit range anyway.
The change to unit range also resolves a bug in the polyblep triangle waveform's leaky integration code. The leaky integration line …

Fix polyblep triangle implementation

---

Source/Synthesis/oscillator.cpp
Source/Utility/dsp.h

Adds a `fastmod1f` method to the dsp utils header which is significantly faster than `fmodf(x, 1.0f)`, and use this in `Oscillator` for nontrivial performance gains.
This optimization really adds up when processing multiple oscillators in more complex applications and when using block-based DSP instead of sample-by-sample, but even with DaisySP defaults the savings are obvious.
I neglected to add this optimization to `BlOsc` because:
1. The measured performance gains are negligible (the cost of the rest of the DSP outweighs the optimization gain)
2. The sawtooth `fmodf` invocation has a variable second argument (not just 1.0f)
Measured using `CpuLoadMeter` and the basic seed oscillator example from `DaisyExamples` at Sample Rate 48kHz and  Block Size 4, with the POLYBLEP_TRI waveform. …

Improve Oscillator performance by avoiding fmodf

---

Source/Noise/whitenoise.h
Source/Utility/dsp.h

This PR adds a setter for the seed value of the `WhiteNoise` class. Its utility should be self-explanatory.
I've also taken the liberty of correcting #190.

Seed setter for `WhiteNoise`

---

CMakeLists.txt
Makefile
Source/Filters/ladder.cpp
Source/Filters/ladder.h
Source/daisysp.h

Adds a new, MIT-licensed ladder filter implementation with additional features and stability compared to the previous DaisySP moogladder (now in LGPL modules).
This implementation is  ported from MIT-licensed code in the Teensy Audio Library, with the implementation derived from work in [this paper](https://www.jstor.org/stable/3682001) from Computer Music Journal by Välimäki and Huovilainen.
This version brings the following advantages:
- Stability across all valid (and internally clamped) parameter ranges
- Stable self oscillation at higher resonances
- 4x linear oversampling for aliasing mitigation
- Input drive and passband gain adjustment
- Filter mode selection (LP/BP/HP 2- or 4-pole outputs)
- Could also provide parallel outputs with some additional modification
However it is a …

Add alternate MIT-licensed ladder filter module

---

Source/Utility/dcblock.cpp

The current `DcBlock` implementation in DaisySP is aggressively rolling off low frequencies. This is due to the fixed coefficient of `0.99` being used instead of one dynamically calculated based on the sample rate and approximate target corner frequency.
This change adds a dynamic pole calculation based on an approximate corner frequency of 10Hz at the given sample rate using `1 - fc/fs` which is fairly reasonable for corner frequencies below ~100Hz. The exact -3dB corner frequency of the original one-pole lowpass filter can be calculated exactly, but the curve changes when subtracting the filtered signal from the original to achieve a DC-blocking highpass as done here.
For reference, here is the filter amplitude response (at fs = 48kHz) with the original hard-coded pole coefficient of …

Fix aggressive low-end rolloff in `DcBlock`
